apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    run: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: app:0.0.1
        ports:
        - containerPort: 3000
